### ISSUE TITLE
Error installing from mamba 

### ISSUE THREAD

**Issue by elizabethmcd** [raw-lab/MetaCerberus#1]
Using the command given in the README: 
```
mamba create -n metacerberus -c bioconda -c conda-forge metacerberus
```

I get the error: 
```
Encountered problems while solving:
  - nothing provides gcc needed by metacerberus-0.1-pyh5e36f6f_0
```

I'm using mamba v0.15.3

**Comment by raw-lab** [comment]
Thank you for using MetaCerberus. 
Can you provide which operating system (linux, mac, windows) you are using?
It appears it cant find the gcc. Can you run this in your terminal? gcc --version

**Comment by raw-lab** [comment]
It appears you may not have a gcc compiler installed. If you on a linux/ubuntu system you would install it with -> sudo apt-get install gcc 
Then try to install again. If it doesnt work send us the version it installs for gcc.

**Comment by raw-lab** [comment]
Did the gcc work? Let us know if this resolved your issue? If not, we can re-open this. 

Thank you for using MetaCerberus. 

Let us know if you were unable to install? We are more than happy to help or do an interactive session.  Also, to add we have tested it on mamba 0.27.0. Your mamba may need an update.

**Comment by raw-lab** [comment]
Also, to add we have tested it on mamba 0.27.0. Your mamba may need an update.

**Comment by raw-lab** [comment]
Let us know if you were unable to install? We are more than happy to help or do an interactive session.

**Comment by decrevi** [comment]
Thank you for your feedback, I am curious if you are using a Mac?
Also I have updated the dependencies in the Bioconda recipe file, this should help. It will take a couple of days for the update to go live.

Please let us know if you have any other problems.
