### ISSUE TITLE
glibc version error

### ISSUE THREAD

**Issue by kayanac** [raw-lab/MetaCerberus#10]
Hi,

Thank you for the tool. I am getting the following issue while installing the tool: 
"Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - bioconda::metacerberus -> ray-core -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.27"

I did a quick google search but could not find a solution for this issue.

**Comment by decrevi** [comment]
Hello,
Thank you for your feedback. Can you please post the command that you are using to install MetaCerberus and your Linux version? The output from `cat /etc/lsb-release` would be useful.

Thank you.

**Comment by kayanac** [comment]
Hello,

The version is  DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS".

My command to install Metacerberus was: 
conda create -n metacerberus
conda activate metacerberus
 conda install bioconda::metacerberus 

Thanks

**Comment by decrevi** [comment]
I am still trying to recreate the error, the error might be at least partly due to using conda instead of mamba. Mamba is a replacement package manager for Anaconda that is faster and better at finding dependency compatibility than conda is.

Some of the dependencies for metacerberus are also found in different channels, like conda-forge. If conda-forge is not already in the list of channels in your Anaconda configuration file, `~/.condarc` then they need to be specified manually,

It is possible that conda is trying to install an outdated version of ray-core if the conda-forge channel is not specified, the other possibility is that conda is failing at finding a proper dependency match where mamba might succeed.

Please let me know if this command works for you:
`mamba create -n metacerberus -c bioconda -c conda-forge metacerberus`

**Comment by raw-lab** [comment]
Thank you for using MetaCerberus. Our Ubuntu version is no longer supported or stable. I would recommend Ubuntu 22.04 for most stable release. The 18.04 support ended June 2023. I think this is an Ubuntu version issue. Again I would recommend the update - https://wiki.ubuntu.com/Releases. Then install using mamba over conda.

**Comment by kayanac** [comment]
Hello, thank you for your quick responses but still I could not solve the problem. I am also having issues with mamba.

**Comment by raw-lab** [comment]
type lsa_release -a
send us the output

type python --version
send us the output

type conda update --all
This will update all the conda works. 

after that try to install mamba
1st try -> conda install mamba
If that works then you can install MetaCerberus
2nd try -> sudo conda install mamba
If that works then you can install MetaCerberus

Please send us the error messages.

**Comment by raw-lab** [comment]
My apologies. It's conda not pip for installing mamba.

**Comment by decrevi** [comment]
Please try this command and let us know if it works to install Mamba:
`conda install -n base --override-channels -c conda-forge mamba 'python_abi=*=*cp*'`

**Comment by kayanac** [comment]
Hello,

I tried lsa_release -a and the command not found. Instead I tried cat /etc/lsb-release and the version is Ubuntu 20.04.6 LTS and I updated Ubuntu today. It used to be version 18.04.6. Python version is 3.19.13. 

Still can't install mamba. I tried these commands today earlier and now.  There is a mamba issue and I think ubuntu is also causing some issues while installing the tools.

**Comment by raw-lab** [comment]
Its an Ubuntu version issue likely. 22.04.04 is the current LTS. Try another upgrade. All our systems are on the latest upgrade of 22.04.04 jammy version. After you upgrade run lsb_release -a then mamba will be easier to install.

**Comment by kayanac** [comment]
It just does not upgrade further.

**Comment by kayanac** [comment]
lsb_release -a worked and but the version is stil 20.04.6 LTS

**Comment by raw-lab** [comment]
Where your mamba and ubuntu version solved? 
As this is issue with mamba/Ubuntu not MetaCerberus I am going to close this for now. Once you get mamba working let us know if you have any further issues. 

Thank you for using MetaCerberus!

Cheers
RAW lab
