### ISSUE TITLE
Error in Step-10

### ISSUE THREAD

**Issue by DeaconOfBiology** [raw-lab/MetaCerberus#11]
I got a strange error in step-10.
Here is my line of code to run MetaCerberus:
```
source ray-slurm-metacerberus.sh
metacerberus.py --prodigal data/processed/final_MAGs/all_final_MAGs/fixed_names --hmm "KOFam_all, COG, VOG, PHROG, CAZy" --dir_out /projects/luo_lab/Rogers_SidersViralAnalysis_XXXX_20XX/data/processed/Metabolic_predictions/metacerberus_out/test

```
Here is the error:
![image](https://github.com/raw-lab/MetaCerberus/assets/48442658/708b6979-22aa-4144-8708-181359109690)

**Comment by raw-lab** [comment]
We believe there is something with the header that is causing hmmer to fail. 
Please send a mag that is failing for testing.

**Comment by raw-lab** [comment]
Dr. Rodgers can you send us a couple 100 lines of the mag in question? Also, what program you used to make the mag? We think its a header issue.

**Comment by raw-lab** [comment]
Seeing that it resolved I will close for now. Thank you for using MetaCerberus
