### ISSUE TITLE
can this tool predict genes for a fungi assembly?

### ISSUE THREAD

**Issue by davidmadariaga** [raw-lab/MetaCerberus#14]
it contains 29 contigs, and the size is of 40 mb approximately. Thanks in advance, and sorry if this is a stupid question and sorry also if this part of your github is not for this kind of questions.

Greetings from Chile!

**Comment by raw-lab** [comment]
Should be able too. Use the fraggenescan setting with the ko eukaryotes. Should have 1.3 update soon. It will have more databases.

**Comment by davidmadariaga** [comment]
omg thank you!!!!!!!!!! may the universe bless you

**Comment by davidmadariaga** [comment]
wait, it will probably predict more genes of the assembly if you add it fungal databases, right?

**Comment by raw-lab** [comment]
Youre too kind. Give it a go and let us know? We will have a major update soon with more databases.

**Comment by davidmadariaga** [comment]
ok, i will keep you informed, thanks again!!! :D

**Comment by raw-lab** [comment]
Very welcome!
Let us know how it worked out for you!
If you want us to include custom or other databases or tools related to your work - please let us know?
Closing for now. 

We will let you know when 1.3 is completed.

**Comment by davidmadariaga** [comment]
Hi! it worked!!!!

**Comment by raw-lab** [comment]
Did you get 1.3 installed? You send the contigs over correct? Do you still want us to annotate for you?

Also, have you run our tool metaome stats?
https://github.com/raw-lab/metaome_stats

It will evaluate your assemblies for you. 

Let us know? 

We have tested on diatoms, bats, dogs, mouse. Haven't tested on plants. But, should work for fungi. Let us know?

**Comment by davidmadariaga** [comment]
hi!, yes, i sent the contigs. I used the 1.2 version...the 1.3 includes databases related to fungi? in that case i will update it, but it seems fine for now. I'll have to read the paper in order to better understand the output files haha, but it worked, so i dont think it's necessary that you analyze the assembly, thanks for asking!. I used metaomes, i think it's the default in version 1.2, this is the output, it also seems ok: 

![image](https://github.com/raw-lab/MetaCerberus/assets/25496906/b1abcca4-7836-40ab-a5e4-59121201a012)

**Comment by davidmadariaga** [comment]
thanks for the feedback, you are so kind!

**Comment by raw-lab** [comment]
Install MetaCerberus 1.3 version. That is best version. There is a bioconda bug that is taking forever to fix.

**Comment by davidmadariaga** [comment]
Thanks!
