### ISSUE TITLE
Adding FesNov DB

### ISSUE THREAD

**Issue by giacomomutti** [raw-lab/MetaCerberus#16]
Hey devs! First of all, thanks for this amazing tool! 
I was wondering if besides eggnog you could add the [FesNov gene families database](https://www.nature.com/articles/s41586-023-06955-z) (made from the same group of eggnog). In theory it should be possible to download it from [here](https://novelfams.cgmlab.org/downloads/) but this link is not working for me today. Alternatively, the HMMs can be found [here](https://zenodo.org/records/10242439).

Thank you very much!

**Comment by raw-lab** [comment]
Thank you for your interest in MetaCerberus. Sorry for the delay. We have had a major update in 1.3. Tons of new databases. We are curious what these families provide? 
You can run a custom HMM in 1.3 version. It will be released in BioConda in a couple of days or you can do a manual install. 

many thanks,
RAW lab

Closing for now. Let us know if we can make a custom hmm etc for you?

**Comment by giacomomutti** [comment]
Thank you for the reply! The new option looks very useful, I will test it and let you know. 
The FesNov gene families should represent novel gene families from uncultivated prokaryotic taxa, so I thought it would be definitely interesting to annotate a metagenome with them.
