### ISSUE TITLE
Problem with the installation of Metacerberus via Mamba

### ISSUE THREAD

**Issue by ACastellano-hub** [raw-lab/MetaCerberus#18]
Hi, I tried to install Metacerberus using Mamba, as suggested in previous posts, but I keep getting an error related to Ray and grpcio. Does anyone have any suggestions to prevent this error? Thanks in advance!!

Here´s what I run:

mamba create -n metacerberus -c bioconda -c conda-forge metacerberus

Looking for: ['metacerberus']

warning  libmamba Cache file "/home/ach/miniforge3/pkgs/cache/ffeee55f.json" was modified by another program
bioconda/linux-64 (check zst)                       Checked  0.2s
warning  libmamba Cache file "/home/ach/miniforge3/pkgs/cache/2a957770.json" was modified by another program
bioconda/noarch (check zst)                         Checked  0.1s
warning  libmamba Cache file "/home/ach/miniforge3/pkgs/cache/497deca9.json" was modified by another program
warning  libmamba Cache file "/home/ach/miniforge3/pkgs/cache/09cdf8bf.json" was modified by another program
warning  libmamba Cache file "/home/ach/miniforge3/pkgs/cache/0da7e086.json" was modified by another program
genomedk/linux-64 (check zst)                       Checked  0.2s
warning  libmamba Cache file "/home/ach/miniforge3/pkgs/cache/28b07ad4.json" was modified by another program
genomedk/noarch (check zst)                         Checked  0.2s
conda-forge/noarch                                  15.0MB @  33.2MB/s  0.6s
genomedk/linux-64                                   19.4kB @  33.0kB/s  0.6s
genomedk/noarch                                    116.0 B @ 180.0 B/s  0.2s
conda-forge/linux-64                                35.2MB @  45.8MB/s  0.9s
bioconda/noarch                                      5.3MB @   4.0MB/s  1.3s
bioconda/linux-64                                    5.5MB @   4.0MB/s  1.4s
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
└─ metacerberus is not installable because there are no viable options
   ├─ metacerberus [0.1|0.2] would require
   │  └─ ray-dashboard but there are no viable options
   │     ├─ ray-dashboard [1.0.1|1.1.0|...|2.0.0] would require
   │     │  ├─ ray-core [1.0.1 py36hdf6fd44_0|1.0.1 py36hdf6fd44_1|...|1.5.2 py39h714431f_0], which requires
   │     │  │  └─ grpcio [>=1.28.1 |>=1.28.1,<1.48 |>=1.28.1,<=1.43.0 |>=1.28.1,<=1.46.0 ] but there are no viable options
   │     │  │     ├─ grpcio [1.41.1|1.42.0|...|1.54.2] would require
   │     │  │     │  ├─ c-ares >=1.18.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     │  └─ libgrpc [1.51.1 hbc085c6_2|1.51.1 hcf146ea_3|...|1.54.2 hcf146ea_0], which requires
   │     │  │     │     └─ c-ares >=1.18.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.54.3|1.55.0|...|1.58.1] would require
   │     │  │     │  └─ libgrpc [1.54.3 hb20ce57_0|1.55.0 h59456c1_0|...|1.58.1 h30d5116_0], which requires
   │     │  │     │     └─ c-ares >=1.19.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.57.0|1.57.1|...|1.59.2] would require
   │     │  │     │  └─ libgrpc [1.57.0 ha4d0f93_2|1.57.0 hd92f1f0_3|...|1.59.2 hd6c4280_0], which requires
   │     │  │     │     └─ c-ares >=1.20.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.14.1|1.16.0|...|1.30.0] would require
   │     │  │     │  └─ c-ares >=1.15.0,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.31.0|1.32.0|1.33.1|1.33.2] would require
   │     │  │     │  └─ c-ares >=1.16.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.34.0|1.34.1|...|1.38.1] would require
   │     │  │     │  └─ c-ares >=1.17.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.39.0|1.40.0|1.41.0|1.41.1] would require
   │     │  │     │  └─ c-ares >=1.17.2,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio 1.59.3 would require
   │     │  │     │  └─ libgrpc 1.59.3 hd6c4280_0, which requires
   │     │  │     │     └─ c-ares >=1.21.0,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio 1.60.0 would require
   │     │  │     │  └─ libgrpc 1.60.0 hd6c4280_0, which requires
   │     │  │     │     └─ c-ares >=1.22.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.60.0|1.60.1|1.61.0|1.61.1] would require
   │     │  │     │  └─ libgrpc [1.60.0 h74775cd_1|1.60.1 h74775cd_0|1.61.0 hccd595a_0|1.61.1 hccd595a_0], which requires
   │     │  │     │     └─ c-ares >=1.26.0,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     ├─ grpcio [1.61.1|1.61.2|1.62.0|1.62.1] would require
   │     │  │     │  └─ libgrpc [1.61.1 h42401df_1|1.61.2 h42401df_0|1.62.0 h15f2491_0|1.62.1 h15f2491_0], which requires
   │     │  │     │     └─ c-ares >=1.27.0,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  │     └─ grpcio 1.62.2 would require
   │     │  │        └─ libgrpc 1.62.2 h15f2491_0, which requires
   │     │  │           └─ c-ares >=1.28.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  └─ ray-default [1.10.0 py37h89c1867_0|1.10.0 py38h578d9bd_0|...|2.0.0 py39hf3d152e_1], which requires
   │     │     └─ ray-core [1.10.0 py37hf931bba_0|1.10.0 py38h9ba0119_0|...|2.0.0 py39hecbb631_1], which cannot be installed (as previously explained);
   │     ├─ ray-dashboard 2.0.1 would require
   │     │  └─ ray-default [2.0.1 py310hff52083_0|2.0.1 py310hff52083_1|...|2.0.1 py39hf3d152e_1], which requires
   │     │     └─ ray-core [2.0.1 py310h4bbae03_0|2.0.1 py310h4bbae03_1|...|2.0.1 py39hecbb631_1], which requires
   │     │        └─ grpcio >=1.32.0,<1.48 , which cannot be installed (as previously explained);
   │     ├─ ray-dashboard [2.1.0|2.2.0|...|2.8.1] would require
   │     │  ├─ ray-core [2.1.0 py310h62c6cac_1|2.1.0 py38haa881f2_1|...|2.6.3 py39hf5bac6d_1], which requires
   │     │  │  └─ grpcio >=1.42,<1.49 , which cannot be installed (as previously explained);
   │     │  └─ ray-default [2.1.0 py310hff52083_0|2.1.0 py38h578d9bd_0|...|2.8.1 py39hf3d152e_0], which requires
   │     │     ├─ grpcio [>=1.50,<1.56 |>=1.50,<1.58.0b0 ], which cannot be installed (as previously explained);
   │     │     └─ ray-core [2.1.0 py310h4bbae03_0|2.1.0 py310h62c6cac_1|...|2.6.3 py39hf5bac6d_1], which cannot be installed (as previously explained);
   │     └─ ray-dashboard 2.8.0 would require
   │        └─ ray-default 2.8.0 py38h578d9bd_1, which requires
   │           └─ ray-core 2.8.0 py38h1702d6c_1, which does not exist (perhaps a missing channel);
   ├─ metacerberus [0.2|1.0|1.3.0] would require
   │  ├─ grpcio [ |<=1.43.0 ] but there are no viable options
   │  │  ├─ grpcio [1.41.1|1.42.0|...|1.54.2], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.54.3|1.55.0|...|1.58.1], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.57.0|1.57.1|...|1.59.2], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.14.1|1.16.0|...|1.30.0], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.31.0|1.32.0|1.33.1|1.33.2], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.34.0|1.34.1|...|1.38.1], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.39.0|1.40.0|1.41.0|1.41.1], which cannot be installed (as previously explained);
   │  │  ├─ grpcio 1.59.3, which cannot be installed (as previously explained);
   │  │  ├─ grpcio 1.60.0, which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.60.0|1.60.1|1.61.0|1.61.1], which cannot be installed (as previously explained);
   │  │  ├─ grpcio [1.61.1|1.61.2|1.62.0|1.62.1], which cannot be installed (as previously explained);
   │  │  ├─ grpcio 1.62.2, which cannot be installed (as previously explained);
   │  │  └─ grpcio 1.14.1 would require
   │  │     └─ c-ares >=1.14.0,<2.0a0 , which conflicts with any installable versions previously reported;
   │  └─ ray-tune but there are no viable options
   │     ├─ ray-tune [1.0.1|1.1.0|...|2.0.0] would require
   │     │  └─ ray-core [1.0.1 py36hdf6fd44_0|1.0.1 py36hdf6fd44_1|...|2.0.0 py39hecbb631_1], which cannot be installed (as previously explained);
   │     ├─ ray-tune 2.0.1 would require
   │     │  └─ ray-core [2.0.1 py310h4bbae03_0|2.0.1 py310h4bbae03_1|...|2.0.1 py39hecbb631_1], which cannot be installed (as previously explained);
   │     ├─ ray-tune [2.1.0|2.2.0|...|2.8.1] would require
   │     │  ├─ ray-core [2.1.0 py310h4bbae03_0|2.1.0 py38hb9c8dfe_0|2.1.0 py39hecbb631_0], which cannot be installed (as previously explained);
   │     │  └─ ray-default [2.1.0 py310hff52083_1|2.1.0 py38h578d9bd_1|...|2.8.1 py39hf3d152e_0], which cannot be installed (as previously explained);
   │     └─ ray-tune [2.10.0|2.11.0|...|2.9.3] would require
   │        └─ ray-default [2.10.0 py310h8d86c01_0|2.10.0 py311h48098de_0|...|2.9.3 py39h7a4ae58_0], which requires
   │           └─ grpcio [ |<1.58.0b0 ], which cannot be installed (as previously explained);
   └─ metacerberus [1.0|1.1|1.2|1.2.1|1.3.0] would require
      └─ grpcio 1.43.* , which cannot be installed (as previously explained).

**Comment by raw-lab** [comment]
Thank you for using MetaCerberus. We are working on a patch currently. This is security issue in Ray via grpcio. Back to you shortly.

**Comment by decrevi** [comment]
This particular issue might be due to an out of date or corrupt installation of anaconda.
What version do you have of conda and mamba?

This command should give you both:
`mamba -V`

**Comment by ACastellano-hub** [comment]
Thanks for your prompt reply.

These are the versions of mamba and Conda that I have installed.
mamba 1.5.8
conda 24.5.0


Thanks,
Antonio

**Comment by decrevi** [comment]
Can you send me the contents of your ~/.condarc file?
It might have to do with the priority order of the channels.

I was able to re-create your issue by setting `channel_priority: strict` in my .condarc file.
I usually leave it as `channel_priority: disabled`

with the strict setting enabled, I was also able to get MetaCerberus installed by changing the order of the channels in the install command:

`mamba create -n metacerberus -c conda-forge -c bioconda metacerberus`

if you have the line `channel_priority: strict` in your .condarc file, you can also try changing that to `channel_priority: disabled`

Let me know if this helps,
-Jose

**Comment by ACastellano-hub** [comment]
Hi Jose,
Changing the order of the channels in the install command worked for me. Thanks a lot.

Best,
Antonio

**Comment by raw-lab** [comment]
Great! Thank you for using MetaCerberus. Let us know if you have any further questions? 

Closing for now.
