### ISSUE TITLE
Minor bug/suggestion for genbank output

### ISSUE THREAD

**Issue by pck00** [raw-lab/MetaCerberus#21]
Hello! 

Loving the newest feature of getting genbank output files for the annotation.

One small issue: The LOCUS line is missing information on genome length and type (DNA, circular, linear). 
This causes errors with importing these files into Geneious and perhaps other genome viewers. It's easy to fix with a script but would be nice to have included right away in the output.

cheers

**Comment by pck00** [comment]
And a second, more severe bug (or feature?): 

It appears that when fasta files have Ns in the sequence, metacerberus splits those apart in the final genbank output. So instead of one single annotated contig, you end up with many files of various sizes.

**Comment by pck00** [comment]
Oh an a more major bug - the annotations in genbank format also do not come with directional information - so all the annotations face the same directions even if the actual coding sequences do not.

**Comment by decrevi** [comment]
Hello,
Thank you for your feedback!
We will make sure to include these fixes in the next update to MetaCerberus. I will post another comment here when it is ready.

-Jose

**Comment by decrevi** [comment]
Hello,
MetaCerberus 1.4.0 is now live on Bioconda.
Among other changes and improvements, I implemented some of your suggestions here. The GenBank output is still in development, and there are some things that MetaCerberus just cannot guess on so they are left blank. For now it is meant more as a template to make it easier to create a genbank file for importing into other software.

I did fix the directional information issue, please let me know if there are further issues or suggestions.

thank you,
-Jose
