### ISSUE TITLE
Time for looping through several files

### ISSUE THREAD

**Issue by mpdoane2** [raw-lab/MetaCerberus#22]
Hi, I'm attempting get CAZy annotation using: 

**metacerberus.py --prodigal "$file_path" --hmm CAZy --dir_out "$output_dir"**

in which the file_path points towards an fna file of contigs. 
The process has been running for nearly 20 hours, but the time.tsv pipeline is only 9 minutes. 

**hpc-node019     Pipeline_time   0:09:44.052514  /scratch/user/user/cazy_out/cazy_output/SAGCFN_22_01149_S3**

Is there an issue with the next step, saving the graph barcharts?

Thank you
Mike

**Comment by decrevi** [comment]
Hello, I am looking into this. It does seem to be an issue either with the plots or creating the gff/genbank files.

which version of MetaCerberus are you using?

Thank you,
-Jose

**Comment by decrevi** [comment]
Hello,
I have found and fixed the issue. I will push an updated version shortly with this fix, thank you for bringing this to my attention!

-Jose

**Comment by mpdoane2** [comment]
Hi Jose,

Thank you for looking into this so quickly. For your information, the version I have is 1.3.0 March 2024. 

Thank you again. I'll try running this again soon.

Cheers
Mike

**Comment by decrevi** [comment]
Hello,
just FYI version 1.3.1 is available, as well as version 1.3.2-lite, that have this problem fixed. That step should be significantly faster now, especially with larger files.
I am also pushing version 1.4.0 out this week which has further enhancements, including a custom replacement for Ray that should be easier to work with.

I am going ahead and closing this, please do let me know if you continue to have any issues.

Thank you!
-Jose
