### ISSUE TITLE
Running multiple MAGs in one folder

### ISSUE THREAD

**Issue by lcamVz** [raw-lab/MetaCerberus#24]
I have a quick question. When running Metacerberus, I am not sure, but would I need to indicate the folder containing the bins (similar to DRAM) of interest

 example:

metacerberus.py --prodigal metawrap_refine/*.fa --dir_out metacerberus_out --hmm ALL

 Or would I need to have it as a loop??

**Comment by decrevi** [comment]
Hello,
MetaCerberus does accept wildcards in the path for input files, no need for a loop. Your command should work as is.

Thank you, and let me know if you have any issues!
-Jose

**Comment by lcamVz** [comment]
It worked just perfect thank you!. I do have a question regarding the counts tables is there a way to parse thise AMR, KEGGs, CAZY etc with there annotation instead of the database ID? Or how you approach this withing metacerberus.

**Comment by raw937** [comment]
Check the final/ folder it produces it produces an final annotation table that picks the best hit for each ORFs. It also provides the annotation for each database.
