### ISSUE TITLE
Restarting from point when termination occurred

### ISSUE THREAD

**Issue by mpdoane2** [raw-lab/MetaCerberus#25]
Hi,

I'm wondering if there is a way to start the run from a place where the job was terminated. In this instance, my job took longer than anticipated and was terminated due to the maximum time being reached. I can see from the time.tsv file that the final steps were being processed when the job was terminated. 

Thank you
Mike

**Comment by raw937** [comment]
I don't think we have implemented that yet. It's in our list of things to do. Try 1.4 with HydraMPP it's super fast.

**Comment by decrevi** [comment]
Version 1.4.0 has some improvements on this feature, although it is not fully tested and still experimental.

**Comment by raw-lab** [comment]
We are working on a way for it to restart mid-way for MetaCerberus. But, it's currently not ready. We will let you know when it is. However, HydraMPP in 1.4 is so much faster than Ray that it may be better just to re-run it. 

Closing for now. Let us know if you have any other questions?

Thank you for using MetaCerberus.
