### ISSUE TITLE
Bug: Ray incompatibility with pydantic

### ISSUE THREAD

**Issue by kclambi1** [raw-lab/MetaCerberus#3]
Most up to date version of pydantic has conflict with Ray; pydantic has to be downgraded below version 2.  Bug in ray has been documented, but has not been fixed as of yet.  

Workaround is to reinstall a lower version of pydantic with: pip3 install "pydantic<2"

**Comment by raw-lab** [comment]
When is this an issue? We havent seen this in Mac or Linux.

**Comment by kclambi1** [comment]
MacOS Ventura, 13.5.1.  Occurs directly following step 5a, removing N's from contig files.  

Command ran was:  metacerberus.py --prodigal /Users/xxxx/Downloads/ATCC.fna --hmm "VOG, PHROG" --dir_out /Users/xxxx/Downloads/lambda_vir-only_dir

This bug has been documented while initializing Ray: https://github.com/ray-project/ray/issues/37019

Downgrading pydantic to below version 2 corrects this error.

**Comment by raw-lab** [comment]
This line during install will fix the Mac Issue for OSX-ARM (M1/M2) Macs. 
conda install -y -c conda-forge mamba python=3.10 "pydantic<2"

Close for now. Let us know if it doesn't fix it. 

thank you for using MetaCerberus!
Raw lab.
