### ISSUE TITLE
Error when trimming fastq files

### ISSUE THREAD

**Issue by kclambi1** [raw-lab/MetaCerberus#4]
Trimming fastq step errors out with non-zero exit status and does not trim files.  Full traceback:

**STEP 3: Trimming fastq files
Traceback (most recent call last):
  File "/Users/xxxx/miniconda3/envs/metacerberus/bin/metacerberus.py", line 693, in <module>
    sys.exit(main())
  File "/Users/xxxx/miniconda3/envs/metacerberus/bin/metacerberus.py", line 421, in main
    shutil.copy(value, os.path.join(report_path, key, f"qc_{name}.html"))
  File "/Users/xxxx/miniconda3/envs/metacerberus/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/xxxx/miniconda3/envs/metacerberus/lib/python3.10/shutil.py", line 233, in copyfile
    if _samefile(src, dst):
  File "/Users/xxxx/miniconda3/envs/metacerberus/lib/python3.10/shutil.py", line 210, in _samefile
    return os.path.samefile(src, dst)
  File "/Users/xxxx/miniconda3/envs/metacerberus/lib/python3.10/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType**

Something is getting passed as null somewhere, or potentially writing the same file being read?

**Comment by raw-lab** [comment]
What type of fastq are you using (oxford, pacbio, illumina)? 
If you can attach a few hundred reads here if you would like?

**Comment by kclambi1** [comment]
These are nanopore minion reads.

Command:  metacerberus.py --fraggenescan /Users/xxxx/Downloads/fastq_pass/ --nanopore --meta --dir_out /Users/xxxx/Downloads/lambda_vir-only_dir/

So since '--nanopore' is being specified, it is odd.  The trimming output directories are created, however they are empty.


[FAS12900_pass_efb8dd88_0.fastq.zip](https://github.com/raw-lab/MetaCerberus/files/12443789/FAS12900_pass_efb8dd88_0.fastq.zip)

**Comment by raw-lab** [comment]
This is a Mac issues. 
We recommend installing using:
OSX-ARM (M1/M2) protocol on the readme:
conda create -y -n metacerberus
conda activate metacerberus
conda config --env --set subdir osx-64
conda install -y -c conda-forge mamba python=3.10 "pydantic<2"
mamba install -y -c bioconda -c conda-forge metacerberus
metacerberus.py --setup

This should fix the Mac bug. 
If you have any other issues let us know?
Closing for now. Will re-open if you have the issue. 

Thank you for using MetaCerberus. 

many thanks,
RAW lab
