### ISSUE TITLE
databases

### ISSUE THREAD

**Issue by wittney-m** [raw-lab/MetaCerberus#6]
Is there a specific folder that the databases should be placed in?

**Comment by raw937** [comment]
Thank you for using MetaCerberus!
It depends how you installed MetaCerberus. 
But, if you used the mamba approach which we recommend the databases are automatically installed. 
Also, manual install they are also automatically installed. 

By default they would be in lib/python3.9/site-packages/meta_cerberus/DB/ (mamba approach). 

Do you have an error that it can't find the databases?

many thanks,
RAWIII

**Comment by wittney-m** [comment]
Hi,

I downloaded everything manually.

This is the error I am receiving.

HMM: 'KOFam_all'
ERROR: Cannot use 'KOFam_all', please download it using 'metacerberus.py --setup
ERROR: No HMM DB Loaded

**Comment by raw937** [comment]
In order to better help. 
Can you send me the commands you used to install?
You can go to your terminal and type -> history 
If you need to. 

The databases are manually installed if you have conda and/or mamba installed. 

many thanks,
RAWIII

**Comment by wittney-m** [comment]
I downloaded the package on my machine directly from github because I was unable to use mamba or conda.

**Comment by raw937** [comment]
You need to have either mamba or conda installed. The set-up requires it even for manual install. What were your error messages from mamba or conda? 
https://conda.io/projects/conda/en/latest/user-guide/install/index.html

After conda is installed. 
In your terminal - conda install mamba 

Once mamba is install then follow the mamba install guidelines. 

Let me know if you get stuck?
conda can hang sometimes. 

many thanks,
RAWIII

**Comment by raw937** [comment]
Let us know if you have trouble after installing mamba or conda? If you are still having issues please re-open this issue. I am going to close this issue for now. 

Thank you for using MetaCerberus!

many thanks,
RAWIII
