### ISSUE TITLE
bbduk error?

### ISSUE THREAD

**Issue by pck00** [raw-lab/MetaCerberus#7]
Hello, 
Testing out illumina files and running into this error: 

(metacerberus) pck@LSE315-PK:~/metagenome_seq$ metacerberus.py --prodigal ~/metagenome_seq/ --illumina --meta --dir_out test
HMM: 'KOFam_all'

Starting MetaCerberus Pipeline

Checking for external dependencies:
fastqc               /home/pck/anaconda3/envs/metacerberus/bin/fastqc
flash2               /home/pck/anaconda3/envs/metacerberus/bin/flash2
fastp                /home/pck/anaconda3/envs/metacerberus/bin/fastp
porechop             /home/pck/anaconda3/envs/metacerberus/bin/porechop
bbduk.sh             /home/pck/anaconda3/envs/metacerberus/bin/bbduk.sh
FragGeneScanRs       /home/pck/anaconda3/envs/metacerberus/lib/python3.10/site-packages/meta_cerberus/FGS/FragGeneScanRsprodigal             /home/pck/anaconda3/envs/metacerberus/bin/prodigal
prodigal-gv          NOT FOUND, must be defined in config file as EXE_PRODIGAL-GV:<path>
phanotate.py         NOT FOUND, must be defined in config file as EXE_PHANOTATE:<path>
hmmsearch            /home/pck/anaconda3/envs/metacerberus/bin/hmmsearch
countAssembly.py     /home/pck/anaconda3/envs/metacerberus/bin/countAssembly.py
Initializing RAY
2024-02-07 13:23:18,236 INFO worker.py:1612 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
Started RAY single node
Running RAY on 1 node(s)
Using 16 CPUs per node

STEP 1: Loading sequence files:
Processing 2 fastq sequences
Processing 0 fasta sequences
Processing 0 protein sequences
Processing 0 rollup files

STEP 3: Trimming fastq files
Trimming: prodigal_SRR9161505_2 /home/pck/metagenome_seq/SRR9161505_2.fastq
Trimming: prodigal_SRR9161505_1 /home/pck/metagenome_seq/SRR9161505_1.fastq

STEP 4: Decontaminating trimmed files

STEP 5b: Reformating FASTQ files to FASTA format

(rayWorkerThread pid=1356) Command '['/home/pck/anaconda3/envs/metacerberus/bin/bbduk.sh', '-Xmx1g', 'in=/home/pck/metagenome_seq/test/step_03-trim/prodigal_SRR9161505_2/trimmed_prodigal_SRR9161505_2.fastq', 'out=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_2/decon-prodigal_SRR9161505_2.fastq', 'qin=30', 'qtrim=r', 'minlen=50', 'k=31', 'ref=default', 'hdist=1', 'stats=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_2/stats.txt']' returned non-zero exit status 1.
(rayWorkerThread pid=1356) ERROR: Failed to execute:
(rayWorkerThread pid=1356)  ['/home/pck/anaconda3/envs/metacerberus/bin/bbduk.sh', '-Xmx1g', 'in=/home/pck/metagenome_seq/test/step_03-trim/prodigal_SRR9161505_2/trimmed_prodigal_SRR9161505_2.fastq', 'out=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_2/decon-prodigal_SRR9161505_2.fastq', 'qin=30', 'qtrim=r', 'minlen=50', 'k=31', 'ref=default', 'hdist=1', 'stats=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_2/stats.txt']

STEP 7: ORF Finder

STEP 8: HMMER Search

STEP 8: Filtering HMMER results

STEP 9: Parse HMMER results

STEP 10: Creating Reports
Saving Statistics
Creating Rollup Tables
Creating Count Tables
NOTE: PCA Tables created only when there are at least four sequence files.

NOTE: Pathview created only when there are at least four sequence files.

Creating combined sunburst and bargraphs

Finished Pipeline
(rayWorkerThread pid=1346) Command '['/home/pck/anaconda3/envs/metacerberus/bin/bbduk.sh', '-Xmx1g', 'in=/home/pck/metagenome_seq/test/step_03-trim/prodigal_SRR9161505_1/trimmed_prodigal_SRR9161505_1.fastq', 'out=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_1/decon-prodigal_SRR9161505_1.fastq', 'qin=30', 'qtrim=r', 'minlen=50', 'k=31', 'ref=default', 'hdist=1', 'stats=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_1/stats.txt']' returned non-zero exit status 1.
(rayWorkerThread pid=1346) ERROR: Failed to execute:
(rayWorkerThread pid=1346)  ['/home/pck/anaconda3/envs/metacerberus/bin/bbduk.sh', '-Xmx1g', 'in=/home/pck/metagenome_seq/test/step_03-trim/prodigal_SRR9161505_1/trimmed_prodigal_SRR9161505_1.fastq', 'out=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_1/decon-prodigal_SRR9161505_1.fastq', 'qin=30', 'qtrim=r', 'minlen=50', 'k=31', 'ref=default', 'hdist=1', 'stats=/home/pck/metagenome_seq/test/step_04-decontaminate/prodigal_SRR9161505_1/stats.txt']

I've run into this problem with two different illumina SRA files, but no problems previously with long read seq data.

**Comment by raw-lab** [comment]
Good afternoon,

Thank you for using MetaCereberus. 

Can you provide:
OS info (linux, mac, etc)
OS version info (e.g., Ubuntu 20.4)
MetaCerberus version: (e.g., 1.2)

Many thanks,
RAW

**Comment by pck00** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

MetaCerberus: version: 1.2 September 2023

**Comment by raw-lab** [comment]
Update with 1.2.1 this bug was fixed in that. Let us know if you have any other issue and we can reopen this. Closing for now.
