### ISSUE TITLE
COG product name falling off

### ISSUE THREAD

**Issue by vancurens** [raw-lab/MetaCerberus#9]
Version: 1.2.1 
System details: Ubuntu 22

COG product names appear incomplete in the annotation summary file, for instance:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sarah/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sarah/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

locus_tag | FOAM | KEGG | COG | CAZy | PHROG | VOG | Best hit | length_bp | e-value | score | EC_number | product
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NZ_CP064936.1_10 |  |  | COG4769 |   |   |   | COG:COG4769 | 347 | 1.30E-29 | 98.9 |   | ;

</body>

</html>

Output and genome input: [COG_names_issue.zip](https://github.com/raw-lab/MetaCerberus/files/14531079/COG_names_issue.zip)

**Comment by raw-lab** [comment]
thank you for using MetaCerberus. 
We have fixed the bug related to the COG metadata. 
all you need to do is load/activate your metacerberus conda environment and re-run setup. This will fix everything.

```
conda activate metacerberus
metacerberus.py --setup
```

Thank you for using MetaCerberus!
